export const HotelsData = [
    {
        id: 1,
        img: "images/hotel1.jpg",
        title: "Hotels",
        text: "Save on amazing places to stay and explore unique experiences",
      },
]

export const HotelsItem = [
  {
    id:1,
    img:"hotelImages/mangrove.jpg",
    city:"Tagaytay",
    title:"Selectum Mangrove Resort",
    text:"Deluxe Twin Room",
    ratings:"9.5",
    reviews:"superb",
    voucher:"",
    prices:"₱ 3,913",
    dates:"Based on rates from 12 July",
    url:"/"
  },

  {
    id:2,
    img:"hotelImages/taalvista.jpg",
    city:"Tagaytay",
    title:"Taal Vista Hotel",
    text:"Deluxe Twin Room",
    ratings:"8.5",
    reviews:"Good",
    voucher:"",
    prices:"₱ 5,913",
    dates:"Based on rates from 12 July",
    url:"/"
  },

  {
    id:3,
    img:"hotelImages/escala.jpg",
    city:"Tagaytay",
    ratings:"9.5",
    reviews:"superb",
    title:"Escala Hotel Tagaytay",
    text:"Deluxe Room",
    voucher:"",
    prices:"₱ 6,230",
    dates:"Based on rates from 12 July",
    url:"/"
  },

  {
    id:4,
    img:"hotelImages/thelake.jpg",
    city:"Tagaytay",
    ratings:"9.0",
    reviews:"Good",
    title:"The Lake Hotel Tagaytay",
    text:"Deluxe Twin Room",
    voucher:"",
    prices:"₱ 8,230",
    dates:"Based on rates from 12 July",
    url:"/"
  },

  {
    id:5,
    img:"hotelImages/smdc.jpg",
    city:"Tagaytay",
    ratings:"9.0",
    reviews:"superb",
    title:" SMDC Taal Lake Staycation",
    text:"Deluxe Twin Room",
    voucher:"",
    prices:"₱ 3,999",
    dates:"Based on rates from 12 July",
    url:"/"
  },

  {
    id:6,
    img:"hotelImages/radisoncebu.jpg",
    city:"Cebu",
    ratings:"9.0",
    reviews:"superb",
    title:"Radison Blu Cebu",
    text:"Deluxe Twin Room",
    voucher:"",
    prices:"₱ 8,999",
    dates:"Based on rates from 12 July",
  },

  {
    id:7,
    img:"hotelImages/moalboalcebu.jpg",
    city:"Cebu",
    ratings:"9.0",
    reviews:"superb",
    title:"The Secret Paradise Moalboal",
    text:"Deluxe Twin Room",
    voucher:"",
    prices:"₱ 5,999",
    dates:"Based on rates from 12 July",
  },

  {
    id:8,
    img:"hotelImages/oceanvidacebu.jpg",
    city:"Cebu",
    ratings:"9.0",
    reviews:"superb",
    title:"Ocean Vida beach and Dive Resort  ",
    text:"1 Bedroom House",
    voucher:"",
    prices:"₱ 4,999",
    dates:"Based on rates from 12 July",
  },

  {
    id:9,
    img:"hotelImages/costabellacebu.jpg",
    city:"Cebu",
    ratings:"9.0",
    reviews:"superb",
    title:"Costabella Tropical Beach Hotel",
    text:"Deluxe Twin Room",
    voucher:"",
    prices:"₱ 3,999",
    dates:"Based on rates from 12 July",
  },

  {
    id:10,
    img:"hotelImages/beachHousecebu.jpg",
    city:"Cebu",
    ratings:"9.0",
    reviews:"superb",
    title:"Alegria Water front beach house ",
    text:"Deluxe Twin Room",
    voucher:"",
    prices:"₱ 7,500",
    dates:"Based on rates from 12 July",
  },
  {
    id:11,
    img:"hotelImages/hotelboracay1.jpg",
    city:"Boracay",
    ratings:"9.0",
    reviews:"superb",
    title:"The Piccolo Hotel of Boracay",
    text:"Standard Queen Room",
    voucher:"",
    prices:"₱ 2,730",
    dates:"Based on rates from 12 July",
  },
  {
    id:12,
    img:"hotelImages/boracay2.jpg",
    city:"Boracay",
    ratings:"9.0",
    reviews:"superb",
    title:"Boracay Haven Resort",
    text:"Deluxe Double / Twin Room",
    voucher:"",
    prices:"₱ 3,054",
    dates:"Based on rates from 12 July",
  },

  {
    id:13,
    img:"hotelImages/boracay3.jpg",
    city:"Boracay",
    ratings:"9.0",
    reviews:"superb",
    title:"Greenyard Inn",
    text:"Superior Double Room",
    voucher:"",
    prices:"₱ 1,913",
    dates:"Based on rates from 12 July",
  },

  {
    id:14,
    img:"hotelImages/boracay4.jpg",
    city:"Boracay",
    ratings:"9.0",
    reviews:"superb",
    title:"Boracay Haven Resort",
    text:"Deluxe Double / Twin Room",
    voucher:"",
    prices:"₱ 3,054",
    dates:"Based on rates from 12 July",
  },

  {
    id:15,
    img:"hotelImages/boracay5.jpg",
    city:"Boracay",
    ratings:"9.0",
    reviews:"superb",
    title:"Henann Palm Beach Resort",
    text:"Deluxe Room",
    voucher:"",
    prices:"₱ 6,083",
    dates:"Based on rates from 12 July",
  },

  {
    id:16,
    img:"hotelImages/siargao1.jpg",
    city:"Siargao",
    ratings:"9.0",
    reviews:"superb",
    title:"Bamboo Surf Beach",
    text:"Beach Cottage with Full Seaview",
    voucher:"",
    prices:"₱ 4,800",
    dates:"Based on rates from 12 July",
  },

  {
    id:17,
    img:"hotelImages/siargao2.jpg",
    city:"Boracay",
    ratings:"9.0",
    reviews:"superb",
    title:"Henann Palm Beach Resort",
    text:"Deluxe Room",
    voucher:"",
    prices:"₱ 6,083",
    dates:"Based on rates from 12 July",
  },

  {
    id:18,
    img:"hotelImages/siargao3.jpg",
    city:"Siargao",
    ratings:"9.0",
    reviews:"superb",
    title:"Trogon's Perch",
    text:"Deluxe Double Room with Balcony and Sea View",
    voucher:"",
    prices:"₱ 8,925",
    dates:"Based on rates from 12 July",
  },

  {
    id:19,
    img:"hotelImages/siargao4.jpg",
    city:"Siargao",
    ratings:"9.0",
    reviews:"superb",
    title:"Lafinca Hostel Siargao",
    text:"Bed in 8-bed Mixed Dormitory Room",
    voucher:"",
    prices:"₱ 1,400",
    dates:"Based on rates from 12 July",
  },
  {
    id:20,
    img:"hotelImages/siargao5.jpg",
    city:"Siargao",
    ratings:"9.0",
    reviews:"superb",
    title:"Barrel Wood House",
    text:"1 Bedroom House",
    voucher:"",
    prices:"₱ 1,600",
    dates:"Based on rates from 12 July",
  },

  {
    id:21,
    img:"hotelImages/puerto1.jpg",
    city:"Puerto Princesa",
    ratings:"9.0",
    reviews:"superb",
    title:"Aziza Paradise Hotel",
    text:"1 Bedroom House",
    voucher:"",
    prices:" Not Available yet from june 30 to july 4",
    dates:"Based on rates from 12 July",
  },
  {
    id:22,
    img:"hotelImages/puerto2.jpg",
    city:"Puerto Princesa",
    ratings:"9.0",
    reviews:"superb",
    title:"Carpe Diem Villa & Resort",
    text:"Deluxe Double Room",
    voucher:"",
    prices:"₱ 2,948",
    dates:"Based on rates from 12 July",
  },
  {
    id:23,
    img:"hotelImages/puerto3.jpg",
    city:"Puerto Princesa",
    ratings:"9.0",
    reviews:"superb",
    title:"Mariner's Pension House",
    text:"Economy Quadruple Room",
    voucher:"",
    prices:"₱ 2,054",
    dates:"Based on rates from 12 July",
  },
  {
    id:24,
    img:"hotelImages/puerto4.jpg",
    city:"Puerto Princesa",
    ratings:"9.0",
    reviews:"superb",
    title:"Deep Forest Garden Hotel",
    text:"Deluxe Double Room",
    voucher:"",
    prices:"₱ 1,455",
    dates:"Based on rates from 12 July",
  },
  {
    id:25,
    img:"hotelImages/puerto5.jpg",
    city:"Puerto Princesa",
    ratings:"9.0",
    reviews:"superb",
    title:"Palawan Uno Hotel",
    text:"Standard Premium Room",
    voucher:"",
    prices:"₱ 2,337",
    dates:"Based on rates from 12 July",
  },

]

